Nhom05_QuanLyShopQuanAo/Controllers/DangNhapAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nhom05_QuanLyShopQuanAo.Models;

namespace Nhom05_QuanLyShopQuanAo.Controllers
{
    public class DangNhapAdminController : Controller
    {
        // GET: DangNhapAdmin
        private ShopQuanAoDataContext db = new ShopQuanAoDataContext();

        public ActionResult Logout()
        {
            Session["quanly"] = null;

            return RedirectToAction("Index", "Home");
        }


        public ActionResult Login_Admin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login_Admin(string username, string password)
        {
            var user = db.UserAccounts.FirstOrDefault(u => u.TenDangNhap == username && u.MatKhau == password);

            if (user != null)
            {
                if (user.ChucVu == "Nhân viên")
                {
                    Session["quanly"] = user;
                    return Redirect("~/Admin/Home/Index");
                }
                else
                {
                    ViewBag.ErrorMessage = "Tài khoản không có quyền truy cập với vai trò này!";
                    return View();
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Username hoặc Password không đúng!";
                return View();
            }
        }
    }
}

Nhom05_QuanLyShopQuanAo/Views/DangNhapAdmin/Login_Admin.cshtml
@{
    ViewBag.Title = "Login_Admin";
    Layout = null;
}



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <link rel="icon" href="~/imgs/LOGO-removebg-preview.png" type="images/x-icon">
    <link href="~/Content/TranKhangDI_css/LoginNguoiDung_css/LoginNguoiDung.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>

<body>
    <div class="hero">
        <div class="form-box">
            <div style="padding-top:20px;text-align:center">
                <p style="font-size:35px;font-weight:600">ĐĂNG NHẬP</p>
            </div>

            <div class="social-icon">
                <i class="fa-brands fa-google fa-xl" style="cursor: pointer;"></i>
                <i class="fa-brands fa-facebook fa-xl" style="cursor: pointer;"></i>
                <i class="fa-brands fa-github fa-xl" style="cursor: pointer;"></i>
            </div>

            <form id="login" action="@Url.Action("Login_Admin", "DangNhapAdmin")" class="input-group" method="post">
                <input type="text" name="username" class="input-field" placeholder="User id" required />
                <input type="password" id="login-password" name="password" class="input-field" placeholder="Nhập mật khẩu" required />
                <div><input type="checkbox" class="check-box">Remember Password</div>
                <button type="submit" class="submit-btn">Đăng nhập</button>
                @if (ViewBag.ErrorMessage != null)
                {
                    <p style="color:red">@ViewBag.ErrorMessage</p>
                }

            </form>


        </div>
    </div>

</body>

</html>